// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vehicles.Core.Entities;

#nullable disable

namespace Vehicles.Core.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Vehicles.Core.Entities.Boat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Boats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Red"
                        },
                        new
                        {
                            Id = 2,
                            Color = "Blue"
                        },
                        new
                        {
                            Id = 3,
                            Color = "Black"
                        },
                        new
                        {
                            Id = 4,
                            Color = "White"
                        },
                        new
                        {
                            Id = 5,
                            Color = "Black"
                        });
                });

            modelBuilder.Entity("Vehicles.Core.Entities.Bus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Buses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Red"
                        },
                        new
                        {
                            Id = 2,
                            Color = "Blue"
                        },
                        new
                        {
                            Id = 3,
                            Color = "Black"
                        },
                        new
                        {
                            Id = 4,
                            Color = "White"
                        },
                        new
                        {
                            Id = 5,
                            Color = "Black"
                        });
                });

            modelBuilder.Entity("Vehicles.Core.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Headlights")
                        .HasColumnType("bit");

                    b.Property<int>("Wheels")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Red",
                            Headlights = true,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 2,
                            Color = "Blue",
                            Headlights = true,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 3,
                            Color = "Black",
                            Headlights = true,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 4,
                            Color = "White",
                            Headlights = true,
                            Wheels = 4
                        },
                        new
                        {
                            Id = 5,
                            Color = "Black",
                            Headlights = true,
                            Wheels = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
